services:
  db:
    image: postgres:15-alpine
    container_name: pride-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: PrideDB_Secure_Pass2026_xYz
      POSTGRES_DB: pridedb
    ports:
      - "5435:5432" # External port changed to 5435
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgbouncer:
    image: edoburu/pgbouncer
    container_name: pride-pgbouncer
    restart: always
    environment:
      DATABASE_URL: "postgresql://postgres:PrideDB_Secure_Pass2026_xYz@db:5432/pridedb"
      MAX_CLIENT_CONN: 10000
      DEFAULT_POOL_SIZE: 50
      MIN_POOL_SIZE: 20
      RESERVE_POOL_SIZE: 10
      POOL_MODE: transaction # สำคัญมากสำหรับ High TPS
      AUTH_TYPE: scram-sha-256
    ports:
      - "6432:5432"
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4
    container_name: pride-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: Admin_Pride2026_Secure
    ports:
      - "127.0.0.1:8080:80"
    depends_on:
      - db

volumes:
  postgres_data:
